[build]
  # Entra a la carpeta frontend
  base = "frontend"
  
  # Publica el contenido de esa misma carpeta base
  publish = "."
  
  # Sin comando de compilación
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200